### ISSUE TITLE
KeyError: 'unexpected key "module.feat0.conv.weight" in state_dict'

### ISSUE THREAD

**Issue by thefiddler** [alterzero/DBPN-Pytorch#13]
Using pytorch 0.3.1 and torchvision 0.2.0, I am getting the following error when running eval.py:

```bash
Namespace(chop_forward=True, gpu_mode=False, gpus=1, input_dir='Input', model='models/NTIRE2018_x8.pth', model_type='DBPNLL', output='Results/', seed=123, self_ensemble=True, testBatchSize=1, test_dataset='DIV2K_valid_LR_x8', threads=1, upscale_factor=8)
===> Loading datasets
===> Building model
Traceback (most recent call last):
  File "eval.py", line 64, in <module>
    model.load_state_dict(torch.load(opt.model, map_location=lambda storage, loc: storage))
  File "/usr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 522, in load_state_dict
    .format(name))
KeyError: 'unexpected key "module.feat0.conv.weight" in state_dict'
```

I am using the default parameters for the commandline:

```
python eval.py
```

Any ideas?

**Comment by alterzero** [comment]
Do you find the solution? Can you try using python3.5?

**Comment by kairess** [comment]
If you evaluate model on CPU, parameters should be set as below:

```
gpu_mode=False
self_ensemble=False
chop_forward=False
```

and at line 63:

```python
    #model= torch.load(opt.model, map_location=lambda storage, loc: storage)
    model.load_state_dict(torch.load(opt.model, map_location=lambda storage, loc: storage))
```
replace it to:

```python
    state_dict= torch.load(opt.model, map_location=lambda storage, loc: storage)
    # model.load_state_dict(torch.load(opt.model, map_location=lambda storage, loc: storage))
    from collections import OrderedDict
    new_state_dict = OrderedDict()
    for k, v in state_dict.items():
        name = k[7:] # remove `module.`
        new_state_dict[name] = v

    model.load_state_dict(new_state_dict)
```

it should be working 👍 
(And also make sure with pytorch version 0.3.1)
